definitions:
  schema.Demo:
    properties:
      code:
        description: 编号
        type: string
      created_at:
        description: 创建时间
        type: string
      creator:
        description: 创建者
        type: string
      memo:
        description: 备注
        type: string
      name:
        description: 名称
        type: string
      record_id:
        description: 记录ID
        type: string
      status:
        description: 状态(1:启用 2:停用)
        type: integer
    required:
    - code
    - name
    - status
    type: object
  schema.Result:
    properties:
      data:
        type: object
      msg:
        type: string
      success:
        type: boolean
      title:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/demos:
    post:
      description: 向你说描述
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 创建数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.Demo'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.Result'
      summary: 创建单个demo
      tags:
      - Demo
  /api/v1/demos/{id}:
    get:
      description: 向你说描述
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.Demo'
      summary: 查询获取单个demo数据
      tags:
      - Demo
swagger: "2.0"
